allSupplies = [
    "100 Marmitas",
    "2 Carrinhos De Bebê",
    "7 Kg De Guisado",
    "•7 Kg De Pernil De Porco",
    "Abajure Ou Luminária",
    "Abrigo Feminino E Masculino",
    "Absorvente",
    "Absorvente",
    "Absorvente",
    "Absorventes higiênicos",
    "Absorventes higiênicos",
    "Achocolatado",
    "Achocolatado",
    "Achocolatado pronto",
    "Achocolatado pronto",
    "Açucar",
    "Açúcar",
    "Agasalho Masculino G/gg",
    "Agasalhos",
    "Água",
    "Água",
    "Água",
    "Água Mineral",
    "Água Mineral",
    "Água Mineral - 200 Litros",
    "Água Não Potável",
    "Água Não Potável",
    "Agua Potavel",
    "Agua Potavel",
    "Agua Potavel",
    "Água potável",
    "Água potável",
    "Água potável",
    "Água Sanitária",
    "Água Sanitária",
    "Água Sanitária",
    "Agulha Cinza Ou Roxa",
    "Álcool em gel",
    "Álcool em gel",
    "Álcool Em Gel Potes Médios Para Espalha",
    "Álcool Gel",
    "Álcool Líquido",
    "Alface",
    "Alface",
    "Algodão ",
    "Alho",
    "Alho",
    "Alicate de corte",
    "Alimento Perecível",
    "Alimento Perecível",
    "Alimentos",
    "Alimentos",
    "Alimentos Não Perecíveis",
    "Alimentos Não Perecíveis",
    "Alimentos Não Perecíveis",
    "Alimentos para consumo rápido (Leite, bolacha, suco, etc)",
    "Alimentos para consumo rápido (Leite, bolacha, suco, etc)",
    "Amaciante",
    "Antibiótico - Profilaxia Cães",
    "Antipulgas",
    "Antipulgas",
    "Antipulgas - Animais Pequeno Porte",
    "Aparelho De Barbear",
    "Aparelho De Medir Pressão",
    "Aquecedor Elétrico",
    "Aquecedor Elétrico",
    "Areia de gato",
    "Arroz",
    "Arroz",
    "Arroz",
    "Arroz De 1kg",
    "Arroz De 1kg",
    "Assistentes Sociais",
    "Auxiliar Veterinário",
    "Aveia Em Flocos",
    "Azeite",
    "Azeite",
    "Bactrim 400mg",
    "Bactrim Suspensao",
    "Balança",
    "Balança",
    "Balde",
    "Baldes",
    "Baldes",
    "Banana",
    "Banana",
    "Banheira",
    "Banho E Tosa",
    "Banho E Tosa",
    "Barbeador Descartável",
    "Batata",
    "Batata",
    "Batata Doce",
    "Bermuda Masculina",
    "Bermuda Masculina",
    "Bico",
    "Bicos",
    "Biombo",
    "Biombos",
    "Blusa Frio 8 - 16 Anos",
    "Blusão Adulto",
    "Blusão G",
    "Bobina De Sacos Transparentes",
    "Bolacha Doce",
    "Bolacha Doce",
    "Bolachas",
    "Bolacha Salgada",
    "Bolachinha ",
    "Bolinho",
    "Bombona Vazia 20l",
    "Bombril",
    "Brinquedos",
    "Brinquedos para cães",
    "Brinquedos para cães",
    "Brócolis",
    "Bucha",
    "Cadeira De Rodas",
    "Cadeiras (tipo de praia)",
    "Café",
    "Café",
    "Café Solúvel",
    "Cafeteira Industrial",
    "Caixa de areia (gato)",
    "Caixa de areia (gato)",
    "Caixa De Transporte",
    "Caixas de papelão ",
    "Caixas Organizadoras",
    "Calça Com Elástico F E M",
    "Calca De Moletom",
    "Calça De Moletom 7-16 Anos",
    "Calça De Moletom - Feminina",
    "Calça De Moletom - Feminina",
    "Calça De Moletom (g, Gg, Xxg)",
    "Calça De Moletom Masculina",
    "Calçado Feminino",
    "Calçado Infantil (25 A 34)",
    "Calçado Infantil Masculino 33/34",
    "Calçado Maculino 44",
    "Calçado masculino",
    "Calçado masculino",
    "Calçado Masculino (39 A 43)",
    "Calçados",
    "Calçados",
    "Calçados Infantis",
    "Calçados Infantis",
    "Calçados Masculino Acima De 40",
    "Calça Jeans Feminina",
    "Calça Legging",
    "Calça Legging",
    "Calça Masculina",
    "Calça Masculina G",
    "Calça Moletom 10-14",
    "Calça Moletom Feminino",
    "Calça Moletom Feminino",
    "Calça Moletom G",
    "Calça Moletom Gg",
    "Calça Moletom Masculino",
    "Calça Moletom Masculino",
    "Calça Moleton",
    "Calça Moleton",
    "Calça moleton masculina - G",
    "Calça moleton masculina - G",
    "Calças Gg",
    "Calcinha",
    "Calcinha G E Gg",
    "Calcinha Infantil",
    "Calcinhas",
    "Calcinhas Infantis G",
    "Cama alta para cadeirante ",
    "Cama Beliche",
    "Cama De Hospital",
    "Cama Geriatria",
    "Cama Pet",
    "Cama Pet",
    "Camiseta Manga Curta",
    "Camisetas (manga Longa)",
    "Caneta Insulina Glargin (glargina)",
    "Caneta Insulina Lispro Humalog (",
    "Caneta Insulina Tresiba (degludeca)",
    "Caneta Novorapid Flexpen Asparte",
    "Caneta Permanente",
    "Caneta Permanente",
    "Capa De Chuva",
    "Capa De Chuva",
    "Capa De Chuva Pet",
    "Capas de chuva",
    "Carne Em Geral",
    "Carne Em Geral",
    "Carne Frango",
    "Carne Frango",
    "Carne Gado",
    "Carne Gado",
    "Carne Moída",
    "Carne Moída",
    "Casaco De Moletom Feminino",
    "Casaco De Moletom Masculino",
    "Casaco G E Gg Masculino",
    "Casaco Moleton",
    "Casaco Moleton",
    "Casacos masculinos M/G/GG",
    "Casacos Quentes Infantis",
    "Casacos Quentes Para Adultos",
    "Casinha para cachorro ",
    "Casinha Porte P",
    "Cebola",
    "Cebola",
    "Cebolaa",
    "Cenoura",
    "Cesta Básica",
    "Cesta Básica",
    "Cesta Básica",
    "Cestas Básicas",
    "Cestas Básicas",
    "Cestas Básicas",
    "Chá",
    "Chaleira Elétrica",
    "Chinelo 36 Ao 42",
    "Chinelo Masc",
    "Chinelos",
    "Chinelos 36 A 39",
    "Chinelos Feminino",
    "Chinelos masculinos",
    "Chinelos masculinos",
    "Chuchu",
    "Chuleta Suína 10kg",
    "Chupeta/bico",
    "Coberta",
    "Coberta",
    "Coberta Grossa",
    "Cobertas",
    "Cobertores",
    "Cobertores",
    "Cobertores",
    "Cobertores Para Pet",
    "Cobertor Para Pets",
    "Colchão",
    "Colchão",
    "Colchão Piramidal",
    "Colchões",
    "Colchões",
    "Colchões De Espuma",
    "Coleiras",
    "Coleiras",
    "Coleiras Para Pet",
    "Colete Salva Vidas",
    "Colher Descartável",
    "Colheres Descartáveis (grandes/resistentes, Para Refeições)",
    "Colírii Still",
    "Comidas Não Perecíveis",
    "Comidas Não Perecíveis",
    "Complexo Vitamínico Para Cães Sênior",
    "Computador",
    "Condicionador ",
    "Condicionador ",
    "Consultar Necessidade Na Portaria",
    "Copo Isopor",
    "Copos",
    "Copos Descartáveis",
    "Copos Descartáveis",
    "Copos Descartáveis 180ml",
    "Copos Plasticos",
    "Copos Plasticos",
    "Corda de varal",
    "Cordas",
    "Cordas De Varal",
    "Correntes",
    "Cortador De Unha",
    "Cortador de unhas",
    "Cotonete",
    "Creme De Cabelo",
    "Creme de pentear",
    "Creme De Pentear",
    "Cueca",
    "Cueca",
    "Cueca G E Gg",
    "Cueca Infantil Tamanho 6+",
    "Cuecas",
    "Cuecas Adultos G",
    "Cuecas Tamanhos P M G",
    "Curativos",
    "Dersani",
    "Descartáveis",
    "Descartáveis",
    "Desentupidor - Diabo Verde",
    "Desentupidor - Diabo Verde",
    "Desinfetante",
    "Desinfetante",
    "Desodorante ",
    "Desodorante ",
    "Desodorante Aerosol",
    "Desodorante Feminino",
    "Desodorante Masculino",
    "Desodorante roll-on sem álcool",
    "Desodorantes",
    "Desodorantes",
    "Detergente",
    "Detergente",
    "Detergente",
    "Elástico Para Cabelo",
    "Embalagem De Marmita",
    "Embalagem De Marmita",
    "Embalagem descartável para as marmitas",
    "Embalagem descartável para as marmitas",
    "Enfermeiros",
    "Erva Mate",
    "Erva Mate",
    "Escova de cabelo",
    "Escova de cabelo",
    "Escova de dentes",
    "Escova de dentes",
    "Escova de dentes",
    "Escova De Dentes",
    "Escova De Dentes",
    "Escova De Dentes Infantil",
    "Escova De Roupa",
    "Escova De Vaso",
    "Escova De Vaso",
    "Escova E Pente De Cabelo",
    "Escova Para Lavar Roupa",
    "Espaçador Infantil Para Bombinha",
    "Esparadrapo",
    "Esponja",
    "Esponja",
    "Esponjas De Louça",
    "Etiqueta Identificação Voluntários",
    "Extintor",
    "Extintor",
    "Farinha",
    "Farinha",
    "Farinha De Mandioca",
    "Farinha De Milho",
    "Farinha de polenta",
    "Farinha de polenta",
    "Farinha de trigo",
    "Farinha de trigo",
    "Farinha Láctea",
    "Feijão ",
    "Feijão ",
    "Fibra Alimentar Em Pó",
    "Filtro Para Café Tamanho Grande",
    "Filtro Para Café Tamanho Grande",
    "Fisioterapeutas",
    "Fita Adesiva Crepe",
    "Fita Dupla Face",
    "Fita Durex larga",
    "Fórmula infantil",
    "Fórmula infantil",
    "Fórmula infantil",
    "Fórmula Infantil (aptamil, Nan, Etc)",
    "Fórmula Número 1 (0-6)",
    "Fralda G",
    "Fralda G",
    "Fralda Geriátrica",
    "Fralda Geriátrica",
    "Fralda Geriátrica G",
    "Fralda Geriátrica Gg",
    "Fralda Geriátrica Gg",
    "Fralda Geriátrica ( Xg)",
    "Fralda Geriátrica ( Xg)",
    "Fralda Gg",
    "Fralda Gg",
    "Fralda Gg (infantil)",
    "Fralda Grande Porte Pet",
    "Fralda M",
    "Fralda M",
    "Fralda M",
    "Fralda P",
    "Fralda P",
    "Fralda RN",
    "Fralda RN",
    "Fraldas",
    "Fraldas",
    "Fraldas",
    "Fraldas Adultas",
    "Fraldas Bebê",
    "Fraldas Bebê",
    "Fraldas Geriátricas",
    "Fralda XG e XXG",
    "Fralda XG e XXG",
    "Freezer 110v",
    "Freezer 110v Ou 220v",
    "Frigobar",
    "Frigobar",
    "Frios",
    "Fronhas",
    "Frutas",
    "Frutas",
    "Galochas Variadas (masculino E Feminino)",
    "Garfo Descartável",
    "Garfo e faca",
    "Gás 45 Kg",
    "Gás De Cozinha",
    "Gasolina",
    "Gatorade/Isotônico",
    "Gaze",
    "Geléia",
    "Gelo",
    "Gilete",
    "Gilete",
    "Glicopan",
    "Guarda Chuva",
    "Guardanapo de papel",
    "Guias De Gatos E Cachorros",
    "Herbalvet Ou Vet+20",
    "Higiene Pessoal",
    "Higiene Pessoal",
    "Inseticida",
    "Insumos Para Internação Veterinário",
    "Iogurte",
    "Itens de higiena pessoal",
    "Itens de higiena pessoal",
    "Itens de limpeza",
    "Itens de limpeza",
    "Itens para criança ",
    "Itraconazol",
    "Ivermectina",
    "Jogo de cartas, baralho, dama e dominó, etc",
    "Jogo de cartas, baralho, dama e dominó, etc",
    "Jogos Para Atividades Com As Crianças",
    "Jornal",
    "Jornal",
    "Kit De Higiene",
    "Kit De Limpeza",
    "Kit Higiene Infantil",
    "Kit Higiene Pessoal",
    "Kit Higiene Pessoal",
    "Kits de primeiros socorros",
    "Kits de primeiros socorros",
    "Lâmina De Barbear",
    "Lanches",
    "Lanches",
    "Lanternas",
    "Lanternas",
    "Latas de lixo",
    "Lavanderia",
    "Lavanderia",
    "Legumes",
    "Leite",
    "Leite",
    "Leite",
    "Leite em pó",
    "Leite Em Pó 0 Meses A 12 Anos",
    "Leite Materno",
    "Leitos para animais",
    "Leitos para animais",
    "Lenço De Cima",
    "Lençóis",
    "Lençol",
    "Lençol De Casal",
    "Lençol De Solteiro",
    "Lençol De Solteiro Com Elástico",
    "Lenços umedecidos",
    "Lenço Umedecido",
    "Lenço Umedecido",
    "Lenço Umedecido",
    "Lentilha",
    "Lingerie",
    "Linguiça",
    "Livros",
    "Lixeira Grande",
    "Lonas",
    "Lonas",
    "Lt Casa Pátio Canil Separado",
    "Luva de Latex Descartável",
    "Luva De Limpeza",
    "Luva De Procedimento",
    "Luva G",
    "Luva Latex",
    "Luvas",
    "Luvas",
    "Luvas De Frio",
    "Luvas De Lã",
    "Luvas Descartáveis",
    "Luvas Limpeza",
    "Luvas para limpeza",
    "Luvas para limpeza",
    "Luvas Para Pegar Gatos",
    "Luz de Emergência",
    "Maçã",
    "Maçarico",
    "Macarrão",
    "Macarrão",
    "Malas de Viagem",
    "Mamadeira",
    "Mamadeira",
    "Mamão",
    "Mandioca",
    "Manta Asfáltica",
    "Mantas Ou Cobertas",
    "Mantas Ou Cobertas",
    "Manteiga De Cacau",
    "Máquina de lavar roupa",
    "Maquina De Lavar Roupas 110 V",
    "Máquina De Secar Roupa 220v",
    "Margarina",
    "Margarina",
    "Marmitas",
    "Marmitas",
    "Marmitas - 100",
    "Marmitas (alimento Para Consumo Rápido)",
    "Marmitas De Isopor",
    "Máscara",
    "Massa",
    "Massa",
    "Massa",
    "Material De Higiene",
    "Material De Higiene",
    "Material De Limpeza",
    "Material Escolar",
    "Medicamentos Comuns",
    "Medicamentos Comuns",
    "Medicamentos prescritos",
    "Medicamentos prescritos",
    "Medicamentos veterinários",
    "Medicamentos veterinários",
    "Médicos",
    "Médicos",
    "Megafone",
    "Meia",
    "Meia",
    "Meia Infantil",
    "Meia Infantil 22-40",
    "Meia Infantil 22-40",
    "Meias",
    "Meias",
    "Meias Infantil E Adulto",
    "Meias Infantil E Adulto",
    "Meloxitan Injetável",
    "Mesas Infantis",
    "Micropore",
    "Mistura Salgada Para Pães",
    "Moletom Feminino Emasculino",
    "Moletom G/GG ",
    "Moletom G/GG ",
    "Molho de tomate",
    "Molho de tomate",
    "Molho De Tomate",
    "Molho De Tomate",
    "Mop Giratório",
    "Moranga Cabotiá",
    "Mucilon",
    "Nescau",
    "Nescau Em Pó",
    "Nutralife",
    "Oléo",
    "Óleo De Cozinha",
    "Óleo De Cozinha",
    "Óleo De Soja",
    "Óleo De Soja",
    "Ossinho Ou Semelhantes Para Ansiedade",
    "Ovo",
    "Ovos",
    "Ovos (10 Dúzias)",
    "Pá de lixo",
    "Pá De Lixo",
    "Pães",
    "Palets",
    "Palets",
    "Pallets",
    "Pallets",
    "Pamada Para Bebê",
    "Pano de chão",
    "Pano de chão",
    "Pano de limpeza",
    "Pano de prato",
    "Pano Para Pet",
    "Panos De Chão",
    "Pão",
    "Pão De Sanduíche",
    "Papelão",
    "Papelão",
    "Papel higiênico",
    "Papel higiênico",
    "Papel higiênico",
    "Papel Para Secar Mão",
    "Papel Para Secar Mão",
    "Papel toalha",
    "Paracetamol em gotas",
    "Parvovirose",
    "Pás",
    "Pasta de dente",
    "Pasta de dente",
    "Pasta de dente",
    "Pasta De Dente",
    "Pasta De Dente",
    "Pasta De Dente Infantil",
    "Pasta De Documento",
    "Pasta Z (fichario)",
    "Pastilha Para Garganta",
    "Peiteira P",
    "Pente",
    "Pente/Escova de cabelo",
    "Pente/Escova de cabelo",
    "Pente Fino",
    "Pente Fino",
    "Petisco Para Animais",
    "Petmilk",
    "Pijamas Inverno",
    "Pimentão",
    "Pinça",
    "Pincel Atômico",
    "Pipoca",
    "Plástico filme",
    "Pó De Café",
    "Pó De Café",
    "Polenta",
    "Polenta",
    "Polenta Grossa",
    "Pomada Nistatina",
    "Pomada para assadura",
    "Pomada para assadura",
    "Pote para comida",
    "Potes (marmitex)",
    "Potes (marmitex)",
    "Potinho De Raçao",
    "Prateleira De Ferro",
    "Prato Descartável",
    "Prato Descartável",
    "Pratos",
    "Pratos",
    "Pratos-copos-talheres-guardanapos",
    "Pratos Descartáveis",
    "Prednizolona Para Animais",
    "Prendedor de roupas",
    "Prestobarba",
    "Presunto",
    "Produto De Limpeza",
    "Produto De Limpeza",
    "Produtos de desinfecção (cloro, álcool)",
    "Produtos de desinfecção (cloro, álcool)",
    "Produtos De Limpeza",
    "Produtos De Limpeza",
    "Produtos Perecíveis",
    "Proteínas",
    "Proteínas",
    "Protetor Auricular Para Ruídos",
    "Protetor De Calcinha",
    "Psicólogos",
    "Psicólogos",
    "Queijo",
    "Ração ",
    "Ração ",
    "Ração ",
    "Ração Cachorro",
    "Ração Cachorro",
    "Ração Cachorro",
    "Ração Cão Raças Pequenas",
    "Ração Cão Raças Pequenas",
    "Ração Filhote Gatos",
    "Ração Filhote Gatos",
    "Ração Gastro Intestinal",
    "Ração Gastro Intestinal Para Gato (seca E Lata)",
    "Ração gato",
    "Ração Gato",
    "Ração Gatos",
    "Ração Senior",
    "Ração Senior",
    "Ração úmida",
    "Ração úmida",
    "Refrigerante pequeno",
    "Remédio para piolho",
    "Remédios básicos",
    "Remédios básicos",
    "Remédios básicos",
    "Remédios para pets",
    "Remédios para pets",
    "Repelente",
    "Repelente ",
    "Repelente Infantil",
    "Repolho",
    "Rodo",
    "Roupa Bebê 0-01 Ano",
    "Roupa Bebê 0-01 Ano",
    "Roupa De Cama",
    "Roupa De Cama",
    "Roupa De Inverno",
    "Roupa De Inverno Infantil",
    "Roupa De Inverno Infantil",
    "Roupa De Inverno Infantil 3 A 12 Anos",
    "Roupa Feminina",
    "Roupa Feminina",
    "Roupa Feminina P",
    "Roupa Feminina Plus Size",
    "Roupa Infantil 10-14 Anos",
    "Roupa Infantil 1-3 Anos",
    "Roupa Infantil 1-3 Anos",
    "Roupa Infantil (4 A 10)",
    "Roupa Infantil 7-8 Anos",
    "Roupa Infantil Até 12 Anos",
    "Roupa Infantil Menina",
    "Roupa Infantil Menino",
    "Roupa Infantil Menino",
    "Roupa Infantil (todas Idades)",
    "Roupa íntima ",
    "Roupa íntima ",
    "Roupa Íntima (adulto) Feminina E Masculina",
    "Roupa íntima feminina",
    "Roupa íntima feminina",
    "Roupa Íntima Feminina",
    "Roupa Íntima Infantil",
    "Roupa Íntima Infantil",
    "Roupa íntima masculina",
    "Roupa íntima masculina",
    "Roupa íntima masculina e feminina",
    "Roupa Intima - Menina",
    "Roupa Masculina",
    "Roupa Masculina",
    "Roupa Masculina Adulta",
    "Roupa Masculina De Frio M-g",
    "Roupa Masculina G",
    "Roupa Masculina G E Gg",
    "Roupa Masculina Gg",
    "Roupa Masculina M",
    "Roupa Masculina M",
    "Roupa Masculina Para Frio (todos Tamanhos)",
    "Roupa Masculina Plus Size",
    "Roupa plus size",
    "Roupas",
    "Roupas",
    "Roupas 1 E 2 Anos De Inverno",
    "Roupas Adolescente",
    "Roupas Bebe",
    "Roupas de Camas ",
    "Roupas De Frio",
    "Roupas De Frio",
    "Roupas De Frio",
    "Roupas De Frio M/g/gg",
    "Roupas De Inverno",
    "Roupas De Inverno Para Crianças, Especialmente Meninos",
    "Roupas Diversas",
    "Roupas Diversas",
    "Roupas Femininas",
    "Roupas Femininas",
    "Roupas Femininas De Frio",
    "Roupas Femininas E Masculinas G E Gg",
    "Roupas femininas G/GG",
    "Roupas femininas G/GG",
    "Roupas Femininas P",
    "Roupas Femininas P",
    "Roupas GG",
    "Roupas Gg E Xg Feminina E Masculina",
    "Roupas grandes",
    "Roupas Infantil",
    "Roupas íntimas",
    "Roupas íntimas",
    "Roupas Íntimas De Criança E Adolescente",
    "Roupas Íntimas Femininas",
    "Roupas Íntimas Femininas",
    "Roupas Intimas Feminino",
    "Roupas Íntimas (masc E Fem)",
    "Roupas Íntimas (masc E Fem)",
    "Roupas Intimas Masculino",
    "Roupas íntimas plus size feminina",
    "Roupas íntimas plus size feminina",
    "Roupas leves",
    "Roupas leves",
    "Roupas Maculinas",
    "Roupas Masculima",
    "Roupas Masculinas De Moletom G A Xxg (casacos E Calças)",
    "Roupas Masculinas De Moletom G A Xxg (casacos E Calças)",
    "Roupas Masculinas P",
    "Roupas Masculinas Todos Os Tamanhos",
    "Roupas Masculinas Todos Os Tamanhos",
    "Roupas para adultos",
    "Roupas para adultos",
    "Roupas para adultos",
    "Roupas para crianças",
    "Roupas para crianças",
    "Roupas para crianças",
    "Roupas para frio",
    "Roupas para frio",
    "Roupas Pet",
    "Roupas plus size",
    "Roupas plus size",
    "Roupas Plus Size",
    "Roupas Plus Size",
    "Roupas plus size feminina",
    "Roupas plus size feminina",
    "Roupas plus size masculino",
    "Roupas plus size masculino",
    "Roupas Quentes Para Crianças (1-16 Anos)",
    "Roupões",
    "Sabão Em Barra",
    "Sabão em pó ",
    "Sabão em pó ",
    "Sabão Em Pó",
    "Sabonete De Rosto",
    "Sabonete glicerinado (para machucados)",
    "Sabonete infantil ",
    "Sabonete infantil ",
    "Sabonete Líquido",
    "Sabonete P/ Bebê",
    "Sabonete P/ Bebê",
    "Sabonetes",
    "Sabonetes",
    "Sabonetes",
    "Sache - Cachorro",
    "Sache - Cachorro",
    "Sachê Para Gato",
    "Saco De Lixo 100l",
    "Saco De Lixo 100l",
    "Saco De Lixo 110l",
    "Saco De Lixo 110l",
    "Saco De Lixo 30l Ou 50l",
    "Saco De Lixo Grande",
    "Saco De Lixo Grande",
    "Sacola Plástica De Mercado",
    "Sacolas ou sacos plásticos ",
    "Sacolas ou sacos plásticos ",
    "Sacolas Para Montar Kits",
    "Sacolas Para Montar Kits",
    "Sacolinhas plasticas para kits ",
    "Saco Plástico 5kg",
    "Saco Plástico Pequeno",
    "Sacos 200l",
    "Sacos de lixo",
    "Sacos de lixo",
    "Sacos De Lixo 50l E 100l",
    "Sacos De Lixo Fortes (100l E 200l)",
    "Sal",
    "Sal",
    "Saladas",
    "Sapato Masculino ",
    "Sapato Masculino ",
    "sapatos masculinos - tênis",
    "Saquinhos Para Montar Kit Higiene",
    "Saquinhos Para Montar Kit Higiene",
    "Sardinha",
    "Secador De Cabelo",
    "Secador De Cabelo",
    "Segurança Para O Local",
    "Seringa 10ml",
    "Seringa 1ml",
    "Seringa 3 E 5ml Com Agulha 70x30",
    "Seringa 5ml",
    "Seringa De Insulina",
    "Serragem",
    "Shampoo",
    "Shampoo",
    "Shampoo Em Embalagens Pequenas",
    "Shampoo Infantil",
    "Shampoo Infantil",
    "Shampoo Para Piolho",
    "Shampoo P/ Bebê",
    "Simparic",
    "Solução Otológica (para Limpar Ouvido)",
    "Soro",
    "Soro Fisiológico",
    "Suco de caixinha",
    "Suco Em Pó",
    "Sucos",
    "Sucos",
    "Sucos De Caixinhas",
    "Suplemento Pet",
    "Sutiã",
    "Sutiãs",
    "Talco Infantil",
    "Talco Infantil",
    "Talher Descartável ",
    "Talheres",
    "Talheres",
    "Talheres Descartáveis",
    "Talheres Descartáveis",
    "Tapete higiênico",
    "Tatames",
    "Técnico De Enfermagem",
    "Técnico De Enfermagem",
    "Técnico De Enfermagem - Noite",
    "Tênis",
    "Tênis 36-39",
    "Tênis 46",
    "Tenis Feminino E Masculino Acima De Tamanho 37",
    "Tenis Feminino E Masculino Acima De Tamanho 37",
    "Tenis Feminino E Masculino Todos Os Tamanhos",
    "Tenis Feminino E Masculino Todos Os Tamanhos",
    "Tênis Infantil",
    "Tênis (masc/fem/inf)",
    "Tênis Masculino (38 E Maiores)",
    "Termômetro",
    "Termômetro",
    "Teste De Cinomose",
    "Teste De Fiv E Felv",
    "Toalha de Banho",
    "Toalha de Banho",
    "Toalha De Rosto",
    "Toalha De Rosto",
    "Toalha Para Pet",
    "Toddy",
    "Toddynho",
    "Todynho",
    "Tolhas",
    "Tomate",
    "Tomate",
    "Touca",
    "Touca Descartável",
    "Touca Para Cozinhar",
    "Toucas De Lã",
    "Travesseiro",
    "Travesseiro",
    "Travesseiros",
    "Turno da madrugada",
    "Utensílios Infantis",
    "Vacina Hepatite A",
    "Vacina Para Covid",
    "Vacina Para Influenza",
    "Varal De Roupas",
    "Vassouras",
    "Vassouras e rodos",
    "Vassouras e rodos",
    "Veja Limpeza Pesada",
    "Vela",
    "Ventilador",
    "Verdura",
    "Verdura",
    "Vermífugo",
    "Vermífugo",
    "Veterinários",
    "Veterinários",
    "Vinagre",
    "Vinagre",
    "Vincristina",
    "Voluntário Assistente Social",
    "Voluntário Assistente Social",
    "Voluntário Dentista (fratura)",
    "Voluntário - Madrugada",
    "Voluntário - Madrugada",
    "Voluntário - Manhã",
    "Voluntário - Manhã",
    "Voluntário - Noite",
    "Voluntário - Noite",
    "Voluntário P/ Cuidar Dos Animais",
    "Voluntário P/ Cuidar Dos Animais",
    "Voluntários",
    "Voluntários",
    "Voluntários Médicos",
    "Voluntários Noite",
    "Voluntários Noite",
    "Voluntários para animais",
    "Voluntários para animais",
    "Voluntários Para Cozinha",
    "Voluntários Para Cuidados Com Crianças",
    "Voluntários Para Domingo 12/05 (turno Manhã E Turno Tarde)",
    "Voluntários Para Escala",
    "Voluntários Para Escala",
    "Voluntários Para Instalar Manta Asfáltica",
    "Voluntários Para Organizar Roupas",
    "Voluntários Para Organizar Roupas",
    "Voluntarios Para Pets Turno Da Noite",
    "Voluntários Psicólogos",
    "Voluntários Veterinários",
    "Voluntários Veterinários",
    "Voluntário - Tarde",
    "Voluntário - Tarde",
    "Waffer",
    "Xampu Adulto",
    "Xampu Adulto",
    "Xampu Infantil",
    "Xampu Infantil",
    "Xampu Para Bebês",
    "Xampu Para Piolho",
    "Xampu Para Piolho",
    "Xarope Para Gripe",
    "Xarope Para Gripe",
    "Xarope Para Gripe"
]