allSupplies = [
  "Amaciante",
  "Aparelho De Medir Pressão",
  "Aquecedor Elétrico",
  "Aquecedor Elétrico",
  "Arroz",
  "Arroz",
  "Arroz",
  "Arroz De 1kg",
  "Arroz De 1kg",
  "Assistentes Sociais",
  "Auxiliar Veterinário",
  "Aveia Em Flocos",
  "Azeite",
  "Azeite",
  "Balança",
  "Balança",
  "Banheira",
  "Bico",
  "Bicos",
  "Biombo",
  "Biombos",
  "Bobina De Sacos Transparentes",
  "Bombona Vazia 20l",
  "Bombril",
  "Brinquedos",
  "Bucha",
  "Cadeira De Rodas",
  "Cadeiras (tipo de praia)",
  "Café",
  "Café",
  "Café Solúvel",
  "Cafeteira Industrial",
  "Caixas de papelão ",
  "Caixas Organizadoras",
  "Cama alta para cadeirante ",
  "Cama Beliche",
  "Cama De Hospital",
  "Cama Geriatria",
  "Caneta Permanente",
  "Caneta Permanente",
  "Capa De Chuva",
  "Capa De Chuva",
  "Capas de chuva",
  "Chá",
  "Chaleira Elétrica",
  "Chupeta/bico",
  "Colete Salva Vidas",
  "Colírii Still",
  "Comidas Não Perecíveis",
  "Comidas Não Perecíveis",
  "Complexo Vitamínico Para Cães Sênior",
  "Computador",
  "Condicionador ",
  "Condicionador ",
  "Consultar Necessidade Na Portaria",
  "Correntes",
  "Cortador De Unha",
  "Cortador de unhas",
  "Cotonete",
  "Creme De Cabelo",
  "Creme de pentear",
  "Creme De Pentear",
  "Curativos",
  "Desentupidor - Diabo Verde",
  "Desentupidor - Diabo Verde",
  "Desinfetante",
  "Desinfetante",
  "Detergente",
  "Detergente",
  "Detergente",
  "Elástico Para Cabelo",

  "Enfermeiros",
  "Erva Mate",
  "Erva Mate",
  "Escova de cabelo",
  "Escova de cabelo",
  "Escova de dentes",
  "Escova de dentes",
  "Escova de dentes",
  "Escova De Dentes",
  "Escova De Dentes",
  "Escova De Dentes Infantil",
  "Escova De Roupa",
  "Escova De Vaso",
  "Escova De Vaso",
  "Escova E Pente De Cabelo",
  "Escova Para Lavar Roupa",
  "Espaçador Infantil Para Bombinha",
  "Esparadrapo",
  "Esponja",
  "Esponja",
  "Esponjas De Louça",
  "Etiqueta Identificação Voluntários",
  "Extintor",
  "Extintor",
  "Farinha",
  "Farinha",
  "Farinha De Mandioca",
  "Farinha De Milho",
  "Farinha de polenta",
  "Farinha de polenta",
  "Farinha de trigo",
  "Farinha de trigo",
  "Farinha Láctea",
  "Feijão ",
  "Feijão ",
  "Fibra Alimentar Em Pó",
  "Filtro Para Café Tamanho Grande",
  "Filtro Para Café Tamanho Grande",
  "Fisioterapeutas",
  "Fita Adesiva Crepe",
  "Fita Dupla Face",
  "Fita Durex larga",
  "Freezer 110v",
  "Freezer 110v Ou 220v",
  "Frigobar",
  "Frigobar",
  "Frios",
  "Fronhas",
  "Gás 45 Kg",
  "Gás De Cozinha",
  "Gasolina",
  "Gatorade/Isotônico",
  "Gaze",
  "Geléia",
  "Gelo",
  "Glicopan",
  "Guarda Chuva",
  "Inseticida",
  "Insumos Para Internação Veterinário",
  "Iogurte",
  "Itens de limpeza",
  "Itens de limpeza",
  "Itens para criança ",
  "Itraconazol",
  "Ivermectina",
  "Jogo de cartas, baralho, dama e dominó, etc",
  "Jogos Para Atividades Com As Crianças",
  "Jornal",
  "Jornal",
  "Kit De Limpeza",
  "Kits de primeiros socorros",
  "Kits de primeiros socorros",
  "Lanches",
  "Lanches",
  "Lanternas",
  "Lanternas",
  "Latas de lixo",
  "Lavanderia",
  "Lavanderia",
  "Leitos para animais",
  "Leitos para animais",
  "Lenços umedecidos",
  "Lenço Umedecido",
  "Lenço Umedecido",
  "Lenço Umedecido",
  "Lentilha",
  "Lingerie",
  "Linguiça",
  "Livros",
  "Lixeira Grande",
  "Lonas",
  "Lonas",
  "Lt Casa Pátio Canil Separado",
  "Luva de Latex Descartável",
  "Luva De Limpeza",
  "Luva De Procedimento",
  "Luva G",
  "Luva Latex",
  "Luvas",
  "Luvas",
  "Luvas De Frio",
  "Luvas De Lã",
  "Luvas Descartáveis",
  "Luvas Limpeza",
  "Luvas para limpeza",
  "Luvas para limpeza",
  "Luvas Para Pegar Gatos",
  "Luz de Emergência",
  "Maçarico",
  "Macarrão",
  "Macarrão",
  "Malas de Viagem",
  "Mamadeira",
  "Mamadeira",
  "Mandioca",
  "Manta Asfáltica",
  "Mantas Ou Cobertas",
  "Mantas Ou Cobertas",
  "Manteiga De Cacau",
  "Máquina de lavar roupa",
  "Maquina De Lavar Roupas 110 V",
  "Máquina De Secar Roupa 220v",
  "Máscara",
  "Massa",
  "Massa",
  "Massa",
  "Material De Higiene",
  "Material De Higiene",
  "Material De Limpeza",
  "Material Escolar",
  "Medicamentos veterinários",
  "Medicamentos veterinários",
  "Médicos",
  "Médicos",
  "Megafone",
  "Meloxitan Injetável",
  "Mesas Infantis",
  "Micropore",
  "Mistura Salgada Para Pães",
  "Molho de tomate",
  "Molho De Tomate",
  "Mop Giratório",
  "Moranga Cabotiá",
  "Mucilon",
  "Ovo",
  "Ovos",
  "Ovos (10 Dúzias)",
  "Pá de lixo",
  "Pá De Lixo",
  "Palets",
  "Palets",
  "Pallets",
  "Pallets",
  "Pamada Para Bebê",
  "Pano de chão",
  "Pano de chão",
  "Pano de limpeza",
  "Pano de prato",
  "Panos De Chão",
  "Papelão",
  "Papelão",
  "Parvovirose",
  "Pás",
  "Pasta de dente",
  "Pasta De Dente",
  "Pasta De Dente Infantil",
  "Pasta De Documento",
  "Pasta Z (fichario)",
  "Pente",
  "Pente/Escova de cabelo",
  "Pente/Escova de cabelo",
  "Pente Fino",
  "Pente Fino",
  "Pinça",
  "Pincel Atômico",
  "Pipoca",
  "Plástico filme",
  "Pó De Café",
  "Pó De Café",
  "Polenta",
  "Polenta",
  "Polenta Grossa",
  "Pomada Nistatina",
  "Pomada para assadura",
  "Pomada para assadura",
  "Potinho De Raçao",
  "Prateleira De Ferro",
  "Prendedor de roupas",
  "Presunto",
  "Produtos Perecíveis",
  "Proteínas",
  "Protetor Auricular Para Ruídos",
  "Protetor De Calcinha",
  "Psicólogos",
  "Queijo",
  "Refrigerante pequeno",
  "Repelente",
  "Repelente ",
  "Repelente Infantil",
  "Repolho",
  "Rodo",
  "Roupa De Cama",
  "Roupas de Camas ",
  "Roupões",
  "Sal",
  "Sal",
  "Saladas",
  "Sardinha",
  "Secador De Cabelo",
  "Segurança Para O Local",
  "Serragem",
  "Tatames",
  "Touca",
  "Travesseiro",
  "Touca Para Cozinhar",
  "Toucas De Lã",
  "Utensílios Infantis",
  "Varal De Roupas",
  "Vassouras",
  "Vela",
  "Ventilador",
  "Veterinários",
  "Vinagre",
];
