allSupplies = [
  "Amaciante",
  "Aparelho De Medir Pressão",
  "Aquecedor Elétrico",
  "Aquecedor Elétrico",
  "Arroz",
  "Arroz",
  "Arroz",
  "Arroz De 1kg",
  "Arroz De 1kg",
  "Assistentes Sociais",
  "Auxiliar Veterinário",
  "Aveia Em Flocos",
  "Azeite",
  "Azeite",
  "Balança",
  "Balança",
  "Banheira",
  "Bico",
  "Bicos",
  "Biombo",
  "Biombos",
  "Bobina De Sacos Transparentes",
  "Brinquedos",
  "Bucha",
  "Cadeira De Rodas",
  "Cadeiras (tipo de praia)",
  "Cafeteira Industrial",
  "Caixas de papelão ",
  "Caixas Organizadoras",
  "Capa De Chuva",
  "Capa De Chuva",
  "Capas de chuva",
  "Chá",
  "Chaleira Elétrica",
  "Chupeta/bico",
  "Colete Salva Vidas",
  "Colírii Still",
  "Comidas Não Perecíveis",
  "Comidas Não Perecíveis",
  "Computador",
  "Condicionador ",
  "Condicionador ",
  "Consultar Necessidade Na Portaria",
  "Correntes",
  "Elástico Para Cabelo",
  "Enfermeiros",
  "Erva Mate",
  "Erva Mate",
  "Escova De Roupa",
  "Escova De Vaso",
  "Escova De Vaso",
  "Escova Para Lavar Roupa",
  "Espaçador Infantil Para Bombinha",
  "Esponja",
  "Etiqueta Identificação Voluntários",
  "Extintor",
  "Extintor",
  "Feijão ",
  "Feijão ",
  "Fibra Alimentar Em Pó",
  "Filtro Para Café Tamanho Grande",
  "Filtro Para Café Tamanho Grande",
  "Fisioterapeutas",
  "Freezer 110v",
  "Freezer 110v Ou 220v",
  "Frigobar",
  "Frigobar",
  "Frios",
  "Fronhas",
  "Gás 45 Kg",
  "Gás De Cozinha",
  "Gasolina",
  "Gatorade/Isotônico",
  "Gaze",
  "Geléia",
  "Gelo",
  "Guarda Chuva",
  "Inseticida",
  "Insumos Para Internação Veterinário",
  "Itens para criança ",
  "Jornal",
  "Jornal",
  "Kits de primeiros socorros",
  "Kits de primeiros socorros",
  "Lanches",
  "Lanches",
  "Latas de lixo",
  "Leitos para animais",
  "Leitos para animais",
  "Lentilha",
  "Lixeira Grande",
  "Lonas",
  "Lonas",
  "Lt Casa Pátio Canil Separado",
  "Maçarico",
  "Macarrão",
  "Macarrão",
  "Malas de Viagem",
  "Mamadeira",
  "Mamadeira",
  "Mandioca",
  "Manta Asfáltica",
  "Massa",
  "Massa",
  "Massa",
  "Médicos",
  "Médicos",
  "Megafone",
  "Mesas Infantis",
  "Mistura Salgada Para Pães",
  "Molho de tomate",
  "Molho De Tomate",
  "Ovo",
  "Ovos",
  "Ovos (10 Dúzias)",
  "Palets",
  "Palets",
  "Pallets",
  "Pallets",
  "Papelão",
  "Papelão",
  "Parvovirose",
  "Pás",
  "Pente Fino",
  "Pipoca",
  "Plástico filme",
  "Potinho De Raçao",
  "Prateleira De Ferro",
  "Prendedor de roupas",
  "Presunto",
  "Produtos Perecíveis",
  "Proteínas",
  "Protetor Auricular Para Ruídos",
  "Psicólogos",
  "Queijo",
  "Refrigerante pequeno",
  "Roupa De Cama",
  "Roupas de Camas ",
  "Roupões",
  "Sal",
  "Sal",
  "Sardinha",
  "Secador De Cabelo",
  "Segurança Para O Local",
  "Serragem",
  "Tatames",
  "Touca",
  "Travesseiro",
  "Toucas De Lã",
  "Utensílios Infantis",
  "Varal De Roupas",
  "Ventilador",
  "Veterinários",
  "Vinagre",
];
