SUPPLY_NAME_N0T_MAPPED = [
  "1 Geladeira 110v",
  "20m De Lona Preta",
  "Adrenalina",
  "Agemoxi",
  "Alimentos15 Kg Arroz/dia E 8 Kg Feijão",
  "Alivium Pediátrico",
  "Aparelho Celular",
  "Azitotromicina",
  "Baldes/bacias",
  "Baralho De Uno",
  "Batata Palha",
  "Beterraba",
  "Blusa De Manga Comprida - Menino E Menina - 5 A 16 Anos",
  "Blusa Térmica Feminina G",
  "Blusão, Casaco E Moletom Adulto (todos Os Tamanhos)",
  "Bolsa De Água Quente",
  "Bomba Manual Para Tirar Leite",
  "Bombonas De Água",
  "Bota De Cano Longo De Borracha",
  "Botijão De Gás",
  "Buscopan",
  "Cadeira De Rodas Higiênica Para Banho",
  "Cadernos",
  "Caixa De Ferramentas Básicas",
  "Caixas De Leite",
  "Calçados 38-39-40",
  "Calçados Quentes Fem/masc Adulto E Infantil",
  "Camisetas (manga Longa)",
  "Capacete",
  "Carnes (carne, Frango, Peixe - Proteínas Para Marmitas)",
  "Casaco Jovenil 12/14",
  "Casacos",
  "Casacos E Jaquetas Para Frio Intenso",
  "Celular",
  "Centro Assistencial Paz",
  "Cesto De Alimentos",
  "Chimias / Geleia / Doce De Leite Para Lanche",
  "Cinta Plástica",
  "Clonazepam",
  "Clorofina",
  "Coleiras Antipulgas",
  "Colher Para Refeiçao",
  "Copo Térmico Para Café",
  "Cordões Autismo",
  "Cravulanato 875",
  "Creme Hidratante",
  "Cronidor 80mg",
  "Depakene",
  "Dermotrat Aerosol Para Pet",
  "Desentupidor - Diabo Verde",
  "Dipirona",
  "Dipirona 500mg",
  "Dipirona Gotas",
  "Embalagens Marmitex Descartáveis",
  "Enlatados",
  "Entrega No Ru Saúde (ramiro Barcelos)",
  "Extensão Elétrica",
  "Extensão Elétrica De 5 Metros",
  "Extensões E Adaptadores De 20 A Para Aquecedores",
  "Extrato De Tomate",
  "Filtro De Café Numero 103",
  "Floratil",
  "Focinheira",
  "Fogão",
  "Fraldas Todos Tamanho",
  "Frascos Para Fracionar Shampoo",
  "Frutas (pelo Menos Maçã 4kg, Banana 8 Cachos)",
  "Fórmula Pregomin",
  "Gaze Pct",
  "Guia E Coleira Fortes",
  "Hamburguer",
  "Ibuprofeno 600mg",
  "Iogurte Natural",
  "Itraconazol",
  "Lava Jato 110v",
  "Lava Jato 220v",
  "Leite Condensado",
  "Leite Fórmula",
  "Leite Integral",
  "Leite Ninho Em Pó (para Criança De 2 Anos)",
  "Lista De Necessidades No Instagram Jornal Da Universidade",
  "Lixa de unha",
  "Macacão De Segurança",
  "Macacão para resgate",
  "Maionese",
  "Manteiga",
  "Marmitas ( Arroz, Frango E Legumes)",
  "Meias Grossas",
  "Microondas",
  "Moletom G/GG",
  "Mortadela/presunto/apresuntado",
  "Nimesulida",
  "Notebook",
  "Não Estão Mais Recebendo Abrigados, Pois Estão Aos Poucos Desmontando O Abrigo.",
  "Não Precisa De Doações No Momento",
  "Orelha Desidratada",
  "Panela De Pressão Grande",
  "Penvir",
  "Perfex",
  "Pet Delícia - Alimentação Natural Para Cachorro",
  "Pilha AA",
  "Produto Higiene",
  "Quetiapina",
  "Ração Hipercalórica",
  "Ração Para Cães",
  "Ração Premier Nutrição Clínica",
  "Ração Premium",
  "Recebendo Doações Por 6 Meses Para Atender População Da Enchente",
  "Recovery Ou Comida Pastosa Em Lata - Para Cães",
  "Rodos Grandes",
  "Roupa (fem E Masc) 2 A 12 Anos",
  "Roupa Masculina (inverno E Verão)",
  "Roupas Adolescente",
  "Roupas Bebe (rn)",
  "Roupas G E Gg - Masculino/feminino",
  "Roupas Juvenis Masculinas 12/14 Anos",
  "Roupas grandes",
  "Régua De Luz",
  "Sacola Grande Para Cesta Básica",
  "Salsicha",
  "Salsichão",
  "Sapato Feminino 40/41",
  "Segunda Pele Masculino E Feminino Todos Os Tamanhos",
  "Simparic",
  "Simparic Porte G",
  "Sopão (kit Sopa)",
  "Suco Sem Açucar",
  "Suporte Bombona De Água Mineral 10 /20l",
  "Telefone",
  "Televisão",
  "Teste Rápido Leptospirose",
  "Tinta",
  "Toalhas",
  "Tramadol 50mg E 100mg",
  "Trophic Soya",
  "Tênis Adulto",
  "Veja Limpeza Pesada",
  "Vermífugo Pra Gato",
  "Vincristina",
  "Voluntário Com Carro (4x4 E/ou Caminhão Pequeno Para Regiões De Dificil Acesso)",
  "Voluntário Triagem Doações",
  "Voluntários Para Domingo 12/05 (turno Manhã E Turno Tarde)",
  "Vonal Flash (ondansetrona) 4mg",
  "Xarope Guaco",
  "Água Destilada Injetável",
  "Água Mineral Para Encher Bombonas De 20l",
  "Óleo Mineral"
]
